# -*- coding: utf-8 -*-
"""M13 大纲文档渲染器：课程卡 -> 课件制作大纲.md + 配套练习生成大纲.md
严格按 00_格式规范 两份模板 §1-§9 逐节对应。
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))

def _tier_params(tier):
    if tier == "基础":
        return {"vocab_rate": "15%", "difficulty": "易为主", "grammar_ceiling": "八上 U2"}
    if tier == "中等":
        return {"vocab_rate": "17%", "difficulty": "易中各半", "grammar_ceiling": "八上 U2"}
    return {"vocab_rate": "20%", "difficulty": "中为主+2道推断/态度难题", "grammar_ceiling": "不受限"}

def render_courseware_outline(card, out_path=None):
    lesson = card["lesson"]
    student = card["student"]
    tier = card["tier"]
    theme = card["theme"]
    gnames = card["grammar"]
    ph = card["phonics"]
    new_count = card["vocab"]["new_count"]
    review_count = card["vocab"].get("review_count", 0)
    listening = card.get("listening", False)
    tp = _tier_params(tier)

    md = []
    md.append("# 第 %d 课时 · 课件制作大纲" % lesson)
    md.append("")
    md.append("> **本文档是课件生成的唯一权威规格（Single Source of Truth）。**")
    md.append("> 任何 AI 依据本文档生成 HTML 课件时，必须：① 逐条满足「§3 铁律合规清单」；② 严格实现「§4 结构总览」「§6 逐页明细」「§7 创意交互」；③ 内容数据一律取自「§5 内容载荷」，不得自行编造语篇（真题母本改编红线）。")
    md.append("")
    md.append("## §1 基本信息")
    md.append("")
    md.append("| 项 | 值 |")
    md.append("|---|---|")
    md.append("| 学生 | %s |" % student)
    md.append("| 课时 | 第 %d 课时 |" % lesson)
    md.append("| 难度层级 | %s |" % tier)
    md.append("| 教材锚点 | Stage %s |" % card["stage"])
    md.append("| 主题 | %s |" % theme)
    md.append("| 新词数 | %d（%d 新＋%d 巩固） |" % (new_count + review_count, new_count, review_count))
    md.append("| 语法考点 | ①%s ②%s ③%s |" % (gnames[0], gnames[1], gnames[2]))
    md.append("| 自然拼读 | %s |" % ph)
    md.append("| 听力开关 | %s |" % ("含" if listening else "不含"))
    md.append("| 交付文件 | `%s/第%02d课时/第%02d课时_课件_%s.html` |" % (student, lesson, lesson, tier))
    md.append("")
    md.append("## §2 变量赋值表")
    md.append("")
    md.append("| 变量 | 含义 | 本课值 |")
    md.append("|---|---|---|")
    md.append("| `{{student_name}}` | 学生姓名 | %s |" % student)
    md.append("| `{{lesson_no}}` | 课时序号 | %d |" % lesson)
    md.append("| `{{tier}}` | 难度层级 | %s |" % tier)
    md.append("| `{{new_word_count}}` | 新词数 | %d |" % new_count)
    md.append("| `{{review_word_count}}` | 巩固词数 | %d |" % review_count)
    md.append("| `{{grammar_1}}` `{{grammar_2}}` `{{grammar_3}}` | 三个语法考点 | %s / %s / %s |" % (gnames[0], gnames[1], gnames[2]))
    md.append("| `{{theme}}` | 主题 | %s |" % theme)
    md.append("| `{{phonics}}` | 拼读组合 | %s |" % ph)
    md.append("| `{{interaction_count}}` | 创意交互数＝新知识点数 | 6 |")
    md.append("| `{{grammar_ceiling}}` | 语法上限 | %s |" % tp["grammar_ceiling"])
    md.append("| `{{listening}}` | 是否含听力 | %s |" % ("是" if listening else "否"))
    md.append("")
    md.append("## §3 铁律合规清单（生成后逐条自检，缺一不可）")
    md.append("")
    md.append("1. 单文件 HTML、UTF-8，体积 **≥153600 字节**；页数 **40–45**，每页 `id=\"pageN\"`（N 自 1 连续）。")
    md.append("2. **0 残留标记**：`L22_`、`clozeTest`、`wordMatch`、`crossGame`、`L22_answers` 均不得出现。")
    md.append("3. `<div>` 开合数量相等；全部内嵌 JS 通过 `node --check`。")
    md.append("4. 选择题答案分布**无主导字母**（A/B/C 大致均衡，五选四允许 1 个 E）。")
    md.append("5. 语法规则用**六色要点卡**（`.rule-card`，用法/构成/易错/例句/注意/口诀 六色）。")
    md.append("6. 典型例句/要点/易错一律 **2 列网格**（`.eg-grid/.kp-grid/.error-grid`），奇数末条跨整行。")
    md.append("7. 阅读语篇**分段**（多 `<p>`）；A/B/C 三篇**文体互异**；生词率 %s。", )
    md.append("8. 创意交互 **3–6 个、跨 3+ 环节、不与其他课重复**，**组件数＝当课新知识点数**；复习段必配 1 个趣味交互。")
    md.append("9. **不超语法上限**（本生＝%s）；禁入：比较级/最高级/将来时/完成时/被动语态/各类从句。" % tp["grammar_ceiling"])
    md.append("10. 题干选项**英文**（中文仅题后小字）；**绝不在学生材料提入学分数**。")
    md.append("11. 复习导入**先测后学**：翻牌自检 → 正确呈现 → 易混预热。")
    md.append("12. 音效三件套：`playCorrect()`（答对）/`playError()`（答错）/`playPageTurn()`（翻页）。")
    md.append("")
    md.append("## §4 课件结构设计（八段式总览）")
    md.append("")
    md.append("| 段 | 名称 | 页数 | 功能 | 必配交互 |")
    md.append("|---|---|---|---|---|")
    md.append("| ① | 复习导入 | 4 | 封面＋目标＋上节词汇语法翻牌自检＋易混预热 | 翻牌＋1 趣味复习组件 |")
    md.append("| ② | 新词＋巩固词 | 6 | 新词 %d＋巩固 %d、速记分组、选词填空、辨析、听写 | 翻牌听写＋快选 |" % (new_count, review_count))
    md.append("| ③ | 语法精讲 | 13 | 3 考点 ×（构成例句／易错口诀色卡／中考小测）＋综合表＋梳理＋真题＋填空 | 每考点 1 个组件 |")
    md.append("| ④ | 随堂演练 | 5 | 选择 28（分 2 页）＋中译英＋语法填空＋改错 | 翻牌核对 |")
    md.append("| ⑤ | 阅读理解 | 8 | A/B 篇章＋题、C 五选四、SOP、细节再练 | 定位互动 |")
    md.append("| ⑥ | 自然拼读 | 3 | 组合发音＋演练＋儿歌 | 跟读卡 |")
    md.append("| ⑦ | 课堂练习 | 3 | 跨课快选 ×2＋听音选词 | 快选组件 |")
    md.append("| ⑧ | 课堂总结 | 3 | 知识图谱＋易错清单＋下节预告＋作业 | — |")
    md.append("")
    md.append("**动态页数分配规则**：新词页数＝ceil(新词数/10)，巩固词页数＝ceil(巩固词数/10)；增减的页数在段④随堂题量与段⑦练习间对等调节，总页数恒定 40–45。")
    md.append("")
    md.append("## §5 内容载荷（生成的全部文字数据；语篇仅真题母本改编）")
    md.append("")
    md.append("### 5.1 新词卡 ×%d（格式：单词｜音标｜词性｜中文｜搭配｜例句｜记忆钩）" % new_count)
    md.append("")
    md.append("> 词表经**全课时去重注册表**校验，与 L1–L4 零重复。")
    md.append("")
    md.append("### 5.2 巩固词 ×%d（本课无；若＞0，来源须标注出自第几课时，并滚动进入听写页）" % review_count)
    md.append("")
    md.append("### 5.3 语法考点 ×3（每考点六段式：构成与用法 → 典型例句×6 → 高频易错×5 → 记忆口诀 → 六色要点卡×6 → 中考考法）")
    md.append("")
    for i, g in enumerate(gnames, 1):
        md.append("**考点%d %s**（按六段式展开）" % (i, g))
    md.append("")
    md.append("### 5.4 阅读语篇 ×3（真题母本改编，各附：原文分段＋题目×5＋中文大意＋长难句拆解＋答案解析＋溯源 ID）")
    md.append("")
    md.append("- **A 篇**（文体：说明文）母本源：{{source_id}}｜生词率：%s" % tp["vocab_rate"])
    md.append("- **B 篇**（文体：记叙文）母本源：{{source_id}}｜生词率：%s" % tp["vocab_rate"])
    md.append("- **C 篇 五选四**（文体：应用文/说明）母本源：{{source_id}}｜4 空 5 项含 1 多余项")
    md.append("")
    md.append("### 5.5 自然拼读：%s（含词族表＋儿歌）" % ph)
    md.append("")
    md.append("### 5.6 题库规模：随堂选择 28（答案分布均衡）＋改错 5＋中译英 14＋语法填空 3＋中考小测 6")
    md.append("")
    md.append("## §6 逐页明细（45 页逐页规格）")
    md.append("")
    md.append("| 页 | 段 | 标题 | 内容要点 | 交互/视觉 |")
    md.append("|---|---|---|---|---|")
    md.append("| 1 | ① | 封面 | 第%d课标题＋新词%d/考点3/页数45 三徽章 | 封面居中，品牌红 |" % (lesson, new_count))
    md.append("| 2 | ① | 学习目标 | 4 项目标＋知识图谱 kmap | 2列网格＋图谱 |")
    md.append("| 3 | ① | 复习检测·翻牌自检 | 上节(L4)词汇语法 8 张翻牌卡 | 翻牌 flipCard |")
    md.append("| 4 | ① | 易混知识预热 | 4 组易混点＋语境示例 | 2列网格＋奶油面板 |")
    md.append("| 5 | ② | 新词①(1–10) | 10 词卡：音标/搭配/例句/记忆钩 | 词卡栅格 |")
    md.append("| 6 | ② | 新词②(11–20) | 同上 | 词卡栅格 |")
    md.append("| 7 | ② | 新词速记·分组策略 | 按主题分组＋高频搭配＋词族扩展 | 2列网格 |")
    md.append("| 8 | ② | 词汇运用·选词填空 | 10 空选词，即时判定 | checkOpt |")
    md.append("| 9 | ② | 近义/形近词辨析 | 6 组成对辨析＋口诀 | 2列网格 |")
    md.append("| 10 | ② | 听写自测 | 15 组中→英翻牌 | 翻牌 |")
    md.append("| 11 | ③ | 考点①构成与用法＋例句 | %s构成＋6 例句＋中考考法 | 2列例句网格 |" % gnames[0])
    md.append("| 12 | ③ | 考点①易错＋口诀＋色卡 | 5 改错＋口诀＋六色卡 | 2列改错网格 |")
    md.append("| 13 | ③ | 考点①中考小测 | 2 题即时判定 | checkOpt |")
    md.append("| 14 | ③ | 考点②构成与用法＋例句 | %s | 同上 |" % gnames[1])
    md.append("| 15 | ③ | 考点②易错＋口诀＋色卡 | 同上 | 同上 |")
    md.append("| 16 | ③ | 考点②中考小测 | 2 题 | checkOpt |")
    md.append("| 17 | ③ | 考点③构成与用法＋例句 | %s | 同上 |" % gnames[2])
    md.append("| 18 | ③ | 考点③易错＋口诀＋色卡 | 同上 | 同上 |")
    md.append("| 19 | ③ | 考点③中考小测 | 2 题 | checkOpt |")
    md.append("| 20 | ③ | 三大考点一览表 | 句型对照表 | 彩色矩阵 |")
    md.append("| 21 | ③ | 三大考点综合梳理 | 5 要点＋速记＋实战例句 | 2列网格 |")
    md.append("| 22 | ③ | 中考真题体验 | 微阅读语法填空 2 题 | checkOpt |")
    md.append("| 23 | ③ | 语法综合填空 | 4 题 | checkOpt |")
    md.append("| 24 | ④ | 随堂演练①(1–14) | 14 选择＋解题锦囊 | checkOpt |")
    md.append("| 25 | ④ | 随堂演练②(15–28) | 14 选择＋解题锦囊 | checkOpt |")
    md.append("| 26 | ④ | 句型操练·中译英 | 14 句翻牌核对 | 翻牌 |")
    md.append("| 27 | ④ | 语法填空演练 | 3 题＋解析 | checkOpt |")
    md.append("| 28 | ④ | 改错专练 | 5 题＋思路 | checkOpt |")
    md.append("| 29 | ⑤ | 阅读A篇章 | 分段原文＋中文大意＋长难句 | 阅读卡 |")
    md.append("| 30 | ⑤ | 阅读A理解题 | 5 题＋答案解析 | checkOpt |")
    md.append("| 31 | ⑤ | 阅读B篇章 | 同上 | 阅读卡 |")
    md.append("| 32 | ⑤ | 阅读B理解题 | 5 题＋解析 | checkOpt |")
    md.append("| 33 | ⑤ | 阅读C五选四篇章 | 4 空 5 项 | 阅读卡 |")
    md.append("| 34 | ⑤ | 阅读C五选四题 | 4 题＋解析 | checkOpt |")
    md.append("| 35 | ⑤ | 阅读解题SOP | 6 步法＋本课提示 | 2列网格 |")
    md.append("| 36 | ⑤ | 细节定位再练 | 7 题 | checkOpt |")
    md.append("| 37 | ⑥ | 拼读·l连缀 | 6 组合发音卡 | 发音卡栅格 |")
    md.append("| 38 | ⑥ | 拼读演练 | 词族表＋口诀 | 2列网格 |")
    md.append("| 39 | ⑥ | 拼读儿歌＋小结 | 儿歌＋8 要点 | 奶油面板 |")
    md.append("| 40 | ⑦ | 跨课快选① | 4 组看中文选英文 | checkOpt＋音效 |")
    md.append("| 41 | ⑦ | 跨课快选② | 4 组 | 同上 |")
    md.append("| 42 | ⑦ | 听音选词·词义匹配 | 4 组 | 同上 |")
    md.append("| 43 | ⑧ | 课堂总结·知识图谱 | 5 节点图谱＋作业＋巩固建议 | kmap |")
    md.append("| 44 | ⑧ | 易错清单回顾 | 10 组错→对 | 2列网格 |")
    md.append("| 45 | ⑧ | 下节课预告 | L%d 语法/新词＋课前任务 | 2列网格 |" % (lesson + 1))
    md.append("")
    md.append("## §7 创意交互点清单（6 个＝新知识点数：3 语法＋词汇主题＋拼读＋复习）")
    md.append("")
    md.append("| # | 名称 | 位置 | 绑定知识点 | 玩法 | 音效/动效 |")
    md.append("|---|---|---|---|---|---|")
    md.append("| 1 | 词汇打地鼠 | P3（复习段） | 上节 L4 词汇 | 地鼠随机冒头带词，点中正确释义得分 | 敲击音＋得分动画 |")
    md.append("| 2 | 食物投篮分类 | P7（新词） | food/drink/fruit 分类 | 拖词卡投进对应篮筐，错投弹回 | 投篮音＋弹回抖动 |")
    md.append("| 3 | 指令对对碰 | P13（祈使句） | 祈使句肯/否定 | 看中文指令点正确英文祈使句 | playCorrect/playError |")
    md.append("| 4 | What 转盘问答 | P16（What） | What 问句 | 转盘停格显示物品，自动生成 What 问答 | 转盘转动音 |")
    md.append("| 5 | 喜好表情投票 | P19（like） | like/don't like | 食物卡拖向 😊/😢 两区，自动造句 | 投票叮声 |")
    md.append("| 6 | l连缀消消乐 | P38（拼读） | bl/cl/fl/gl/pl/sl | 相同连缀词卡配对消除 | 消除音＋连击 |")
    md.append("")
    md.append("> 交互不与其他课时重复；每组件附「知识点回链」，答错自动跳对应讲解页。")
    md.append("")
    md.append("## §8 技术与视觉规范")
    md.append("")
    md.append("- **页面骨架**：`.page`（默认隐藏，`.active` 显示），底部导航 8 段跳转 `jumpToSegment(n)`，翻页 `goToPage(n)`＋`playPageTurn()`。")
    md.append("- **配色**：主品牌红 `#E63946`；六色卡六色体系；奶油底面板 `#FFF8E7`；深色文字 `#2B2D42`。")
    md.append("- **字体**：系统圆体栈；标题 800 字重；正文 ≥16px。")
    md.append("- **音效**：Web Audio 合成，无外链音频；三函数命名固定 `playCorrect/playError/playPageTurn`。")
    md.append("- **判定**：选项按钮统一 `data-correct=\"0|1\"`＋`onclick=\"checkOpt(this)\"`，每题仅 1 个 `data-correct=\"1\"`。")
    md.append("- **图片**：如需配图一律占位框＋中文说明，禁用外部链接。")
    md.append("- **防越级词表（禁入）**：比较级/最高级、will/be going to、have/has＋过去分词、被动语态、宾语/定语/状语从句引导词。")
    md.append("")
    md.append("## §9 给外部 AI 的生成指令（可直接复制）")
    md.append("")
    md.append("> 请严格依据本《课件制作大纲》生成一个单文件 HTML 课件（UTF-8，中文界面，初中生英语教学用）。")
    md.append("> 必须满足：§3 全部 12 条铁律；按 §6 的 45 页逐页实现；§5 的内容数据原样采用不得改写语篇；§7 的 6 个交互全部实现且可玩；§8 的技术规范（含 data-correct/checkOpt/jumpToSegment/三音效函数命名）。")
    md.append("> 生成后请自检：文件≥153600 字节、页数 40–45、无 L22_/clozeTest/wordMatch/crossGame/L22_answers 残留、div 开合相等、JS 无语法错误、答案分布无主导字母。")
    md.append("> 输出仅 HTML 代码，不要解释。")
    md.append("")
    md.append("*模板版本 v1.0 ｜ 2026-08-02 ｜ 配套文件：`00_全局约束与红线.md`、`01_课件格式规范.md`、`02_配套练习格式规范.md`*")
    md.append("")

    text = "\n".join(md)
    if out_path is None:
        out_path = os.path.join(HERE, "第%d课时_课件制作大纲.md" % lesson)
    open(out_path, "w", encoding="utf-8").write(text)
    return out_path

def render_practice_outline(card, out_path=None):
    lesson = card["lesson"]
    student = card["student"]
    tier = card["tier"]
    theme = card["theme"]
    gnames = card["grammar"]
    listening = card.get("listening", False)
    tp = _tier_params(tier)

    md = []
    md.append("# 第 %d 课时 · 配套练习生成大纲（模板）" % lesson)
    md.append("")
    md.append("> **定位**：每课时第 4 个产品文件。结构唯一来源＝`exam_spec_v2026_1.json`（locked 后禁手改）；语篇唯一来源＝真题母本库（溯源 ID 必填）。")
    md.append("")
    md.append("## §1 基本信息")
    md.append("")
    md.append("| 项 | 值 |")
    md.append("|---|---|")
    md.append("| 学生 / 课时 / 层级 | %s / 第 %d 课时 / %s |" % (student, lesson, tier))
    md.append("| 当课语法考点 | ①%s ②%s ③%s |" % (gnames[0], gnames[1], gnames[2]))
    md.append("| 当课主题 | %s |" % theme)
    md.append("| 听力 | %s |" % ("☑ 含（总分 120）" if listening else "☑ 不含（总分 100）"))
    md.append("| 输出文件 | `%s/第%02d课时/第%02d课时_配套练习_%s.docx` |" % (student, lesson, lesson, tier))
    md.append("")
    md.append("## §2 卷面结构映射（来自 exam_spec，不得手改）")
    md.append("")
    md.append("| 部分 | 题型 | 题量×分值 | 小计 | 绑定本课内容 |")
    md.append("|---|---|---|---|---|")
    md.append("| 一 阅读理解 | 选择（A/B/C 三篇文体互异） | 15×2 | 30 | A 说明文 B 记叙文 C 应用文 |")
    md.append("| 一 阅读理解 | 五选四（1 多余项） | 4×2.5 | 10 | 健康饮食建议 |")
    md.append("| 二 语言运用 | 完形填空（10 空） | 10×1.5 | 15 | like/三餐主题语篇 |")
    md.append("| 二 语言运用 | 选词填空（12 选 10，适当形式） | 10×1 | 10 | 本课 20 新词为主 |")
    md.append("| 三 综合技能 | 阅读简答（≤10 词） | 5×2 | 10 | 基于阅读 C 篇 |")
    md.append("| 三 综合技能 | 书面表达（80 词，给要点） | 1×15 | 15 | 主题写作 |")
    md.append("| 四 语法诊断 | 语法复盘（考点1:4/考点2:3/考点3:3，含 2 改错） | 10×1 | 10 | %s |" % "/".join(gnames))
    md.append("| 合计 | | 45 题 | 100 | （含听力时 65 题/120 分） |")
    md.append("")
    md.append("## §3 命题双向细目表（逐题登记，卷末附印）")
    md.append("")
    md.append("| 题号 | 题型 | 分值 | 绑定考点/词 | 难度 | 母本源 ID | 备注 |")
    md.append("|---|---|---|---|---|---|---|")
    md.append("| 1–5 | 阅读 A | 2 | 细节定位×3＋词义猜测×1＋主旨×1 | 易 | {{SRC_A}} | 生词率 %s |" % tp["vocab_rate"])
    md.append("| 6–10 | 阅读 B | 2 | 细节×3＋推断×1＋指代×1 | 易-中 | {{SRC_B}} | |")
    md.append("| 11–15 | 阅读 C | 2 | 细节×3＋标题×1＋态度×1 | 中 | {{SRC_C}} | |")
    md.append("| 16–19 | 五选四 | 2.5 | 逻辑衔接 | 中 | {{SRC_W5}} | 1 多余项 |")
    md.append("| 20–29 | 完形 | 1.5 | 动词×3/名词×3/形副×2/介词×2 | 易-中 | {{SRC_CL}} | 10 空 |")
    md.append("| 30–39 | 选词 | 1 | 本课新词 | 易 | 词库 | 适当形式 |")
    md.append("| 40–44 | 简答 | 2 | ≤10 词 | 中 | 同 C 篇 | |")
    md.append("| 45 | 写作 | 15 | 主题 | — | 原创命题 | 4 要点 |")
    md.append("| 46–55 | 语法复盘 | 1 | %s | 易 | 语法库 | 含改错×2 |" % "/".join(gnames))
    md.append("")
    md.append("> 难度列按层级整体偏移：基础＝易为主；中等＝易中各半；培优＝中为主＋2 道推断/态度难题。")
    md.append("")
    md.append("## §4 语篇载荷（真题母本改编红线）")
    md.append("")
    md.append("1. 四篇语篇（A/B/C＋完形＋选词语段）必须取自**真题母本库**并登记溯源 ID（年份/地区/考试）；禁编造模板文。")
    md.append("2. 生词率 %s（基础档取下限）。" % tp["vocab_rate"])
    md.append("3. 时态红线：本课为 L%d，全现在时，禁过去时。" % lesson)
    md.append("4. 题干选项英文；中文注释仅题后小字。")
    md.append("")
    md.append("## §5 题目载荷与答案分布声明")
    md.append("")
    md.append("- 全部客观题答案分布：A/B/C/D 无主导字母（生成后自动校验，偏差＞20% 重排）。")
    md.append("- 每题附：答案＋依据句（原文行号）＋易错点一句话。")
    md.append("- 改错题格式：句中划错→改正，错处限本课考点。")
    md.append("")
    md.append("## §6 DOCX 格式规范")
    md.append("")
    md.append("卷头（课程名+课时+层级；姓名/得分/用时栏）→ 四部分正文（题号全卷连续 1–55）→ 末页答题卡 → 答案解析页（另起页）→ 命题双向细目表（§3）。字体：中文小四宋体、英文 Times New Roman、题号加粗；A4 页边距 2.54cm。")
    md.append("")
    md.append("## §7 合规自检清单（生成后自动执行，fail-fast）")
    md.append("")
    md.append("☐ 题量/分值合计与 §2 完全一致　☐ 溯源 ID 全部登记　☐ 生词率达标　☐ 答案分布均衡　☐ 时态合规　☐ 无入学分数字样　☐ 语法诊断考点配比 4/3/3　☐ 题号连续无重号　☐ 听力开关与 §1 一致")
    md.append("")
    md.append("## §8 给外部 AI 的生成指令（可直接复制）")
    md.append("")
    md.append("> 请依据本大纲与 exam_spec_v2026_1.json 生成一份湖南省中考英语结构配套练习（DOCX 排版说明见 §6）。")
    md.append("> 硬性要求：卷面结构与 §2 逐行一致；语篇按 §4 红线；答案分布均衡；逐题附答案+依据句+易错点；卷末附 §3 双向细目表；题干英文（中文仅题后小字）。")
    md.append("> 输出：完整的练习卷正文＋答题卡＋答案解析＋细目表，不要解释。")
    md.append("")
    md.append("*模板版本 v1.0 ｜ 2026-08-02 ｜ 结构唯一来源：exam_spec_v2026_1.json*")
    md.append("")

    text = "\n".join(md)
    if out_path is None:
        out_path = os.path.join(HERE, "第%d课时_配套练习生成大纲.md" % lesson)
    open(out_path, "w", encoding="utf-8").write(text)
    return out_path

if __name__ == "__main__":
    card = {
        "lesson": 5, "student": "许颖嘉", "tier": "基础", "stage": "S1", "type": "normal",
        "grammar": ["祈使句基础", "What特殊疑问句", "like的用法"], "theme": "食物与日常",
        "vocab": {"new_count": 20, "review_count": 0, "theme": "food"},
        "phonics": "bl/cl/fl/gl/pl/sl",
        "reading": {"genres": ["记叙文", "说明文", "应用文"], "w5": True, "vocab_rate": "15%"},
        "listening": False,
        "interactions": {"count_equals_new_knowledge_points": True},
        "output": ["html", "docx", "outline_courseware", "outline_practice"]
    }
    out = render_courseware_outline(card)
    print("大纲渲染：%s (%d bytes)" % (out, os.path.getsize(out)))
    out2 = render_practice_outline(card)
    print("练习大纲渲染：%s (%d bytes)" % (out2, os.path.getsize(out2)))
